add cron execution for noop local
noop-cloud/noop-local pull request #59
Opened 2020-10-06 22:31 UTC by derekwolpert

This PR adds cron support for Noop Local. Enhanced visibility into cron execution will be added to the Noop Local Inspector in an upcoming PR.

Here is an example for how terminal output was adjusted to accommodate cron info:

```
Starting 'server' container
Setting cron schedule for task 'cronTask'
Your application dev server is running on https://localnoop.app:1234
You can control the dev sever with the following keyboard commands:
    [ i ] -> Open the inspector
    [ o ] -> Open the dev server
    [ r ] -> Reload the dev server
    [ q ] -> Stop the dev server
6:21 PM - Running task 'cronTask' on cron schedule
Starting 'cronTask' container
Cron task 'cronTask' completed successfully
6:22 PM - Running task 'cronTask' on cron schedule
Starting 'cronTask' container
Cron task 'cronTask' completed successfully
Stopping local dev server
Removed cron schedule for 'cronTask' container
Stopped 'server' container
``

2020-10-07 14:49 UTC, derekwolpert commented
@arbitrarytech Removed cron validation from this PR, and added cron validation to `noop-discovery`: https://github.com/noop-cloud/noop-discovery/pull/10

`noop-discovery` PR will need to be merged and released - and the version of `noop-discovery` used by `noop-local` will need to be updated - before this PR is released.

2020-10-07 19:30 UTC, derekwolpert commented
Latest commit - Added back cron validation, and implemented manual task triggering from the inspector.

2020-10-08 20:03 UTC, arbitrarytech requested changes
Looks good. Minor changes.

2020-10-08 20:03 UTC, arbitrarytech commented on lib/devServer.js
> +        console.log(chalk.red(`Error running task '${container.friendlyName}' - start: ${time}, end: ${moment().format('HH:mm:ss')}`))
Return?

2020-10-09 04:19 UTC, derekwolpert commented
@arbitrarytech Issues should be resolved. Removed the unneeded async method, and improved cron functionality.

Also fixed a bug where tasks without LIFECYCLE methods cause an error in Noop Local.

2020-10-14 19:59 UTC, merged